// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProxy(arg1:string,arg2:string):Promise<main.ProxyEntry>;

export function CreateDesktopShortcut():Promise<void>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.BrowserProfile>;

export function DeleteExtension(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteProxy(arg1:string):Promise<void>;

export function DeleteUserScript(arg1:string):Promise<void>;

export function ExportCookies(arg1:string):Promise<void>;

export function ExportProfile(arg1:string):Promise<void>;

export function GetAutomationInfo():Promise<main.AutomationInfo>;

export function GetAutomationSessions():Promise<Array<main.AutomationSession>>;

export function GetAutomationToken():Promise<string>;

export function GetExtensions():Promise<Array<main.BrowserExtension>>;

export function GetProfiles():Promise<Array<main.BrowserProfile>>;

export function GetProxies():Promise<Array<main.ProxyEntry>>;

export function GetStartupURL():Promise<string>;

export function GetStorageDirectory():Promise<string>;

export function GetStorageMode():Promise<string>;

export function GetUserScriptSource(arg1:string):Promise<string>;

export function GetUserScripts():Promise<Array<main.UserScript>>;

export function ImportCookiesFromFile():Promise<string>;

export function ImportProfile():Promise<void>;

export function ImportUserScriptFromFile():Promise<main.UserScript>;

export function InstallExtensionFromDialog():Promise<main.BrowserExtension>;

export function InstallExtensionFromDirectoryDialog():Promise<main.BrowserExtension>;

export function InstallExtensionFromPath(arg1:string):Promise<main.BrowserExtension>;

export function InstallUserScriptsFromPaths(arg1:Array<string>):Promise<Array<main.ScriptInstallOutcome>>;

export function LaunchBrowser(arg1:string,arg2:string):Promise<void>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function OpenDataDirectory():Promise<void>;

export function OpenDefaultAppsSettings():Promise<void>;

export function RedownloadScriptAssets(arg1:string):Promise<main.UserScript>;

export function RegisterAsDefaultBrowser():Promise<string>;

export function ResetCookies(arg1:string):Promise<void>;

export function RotateAutomationToken():Promise<string>;

export function SaveUserScript(arg1:string,arg2:string):Promise<main.UserScript>;

export function SetAutomationEnabled(arg1:boolean):Promise<void>;

export function SetExtensionEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetProfileExtensions(arg1:string,arg2:Array<string>):Promise<void>;

export function SetProfileScripts(arg1:string,arg2:Array<string>):Promise<void>;

export function SetUserScriptEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetUserScriptWorld(arg1:string,arg2:string):Promise<void>;

export function StartAutomationSession(arg1:string,arg2:string):Promise<main.AutomationSession>;

export function StopAutomationSession(arg1:string):Promise<void>;

export function SyncCookies(arg1:string):Promise<void>;

export function TestProxy(arg1:string):Promise<string>;

export function TestProxyEntry(arg1:string):Promise<string>;

export function UnregisterAsDefaultBrowser():Promise<string>;

export function UpdateProfile(arg1:main.BrowserProfile):Promise<void>;

export function UpdateProxy(arg1:main.ProxyEntry):Promise<void>;

export function InstallFromDroppedPaths(arg1:Array<string>):Promise<Array<main.DropOutcome>>;
