// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxy(arg1, arg2) {
  return window['go']['main']['App']['AddProxy'](arg1, arg2);
}

export function CreateDesktopShortcut() {
  return window['go']['main']['App']['CreateDesktopShortcut']();
}

export function CreateProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteExtension(arg1) {
  return window['go']['main']['App']['DeleteExtension'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function DeleteUserScript(arg1) {
  return window['go']['main']['App']['DeleteUserScript'](arg1);
}

export function ExportCookies(arg1) {
  return window['go']['main']['App']['ExportCookies'](arg1);
}

export function ExportProfile(arg1) {
  return window['go']['main']['App']['ExportProfile'](arg1);
}

export function GetAutomationInfo() {
  return window['go']['main']['App']['GetAutomationInfo']();
}

export function GetAutomationSessions() {
  return window['go']['main']['App']['GetAutomationSessions']();
}

export function GetAutomationToken() {
  return window['go']['main']['App']['GetAutomationToken']();
}

export function GetExtensions() {
  return window['go']['main']['App']['GetExtensions']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetProxies() {
  return window['go']['main']['App']['GetProxies']();
}

export function GetStartupURL() {
  return window['go']['main']['App']['GetStartupURL']();
}

export function GetStorageDirectory() {
  return window['go']['main']['App']['GetStorageDirectory']();
}

export function GetStorageMode() {
  return window['go']['main']['App']['GetStorageMode']();
}

export function GetUserScriptSource(arg1) {
  return window['go']['main']['App']['GetUserScriptSource'](arg1);
}

export function GetUserScripts() {
  return window['go']['main']['App']['GetUserScripts']();
}

export function ImportCookiesFromFile() {
  return window['go']['main']['App']['ImportCookiesFromFile']();
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ImportUserScriptFromFile() {
  return window['go']['main']['App']['ImportUserScriptFromFile']();
}

export function InstallExtensionFromDialog() {
  return window['go']['main']['App']['InstallExtensionFromDialog']();
}

export function InstallExtensionFromDirectoryDialog() {
  return window['go']['main']['App']['InstallExtensionFromDirectoryDialog']();
}

export function InstallExtensionFromPath(arg1) {
  return window['go']['main']['App']['InstallExtensionFromPath'](arg1);
}

export function InstallUserScriptsFromPaths(arg1) {
  return window['go']['main']['App']['InstallUserScriptsFromPaths'](arg1);
}

export function LaunchBrowser(arg1, arg2) {
  return window['go']['main']['App']['LaunchBrowser'](arg1, arg2);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function OpenDataDirectory() {
  return window['go']['main']['App']['OpenDataDirectory']();
}

export function OpenDefaultAppsSettings() {
  return window['go']['main']['App']['OpenDefaultAppsSettings']();
}

export function RedownloadScriptAssets(arg1) {
  return window['go']['main']['App']['RedownloadScriptAssets'](arg1);
}

export function RegisterAsDefaultBrowser() {
  return window['go']['main']['App']['RegisterAsDefaultBrowser']();
}

export function ResetCookies(arg1) {
  return window['go']['main']['App']['ResetCookies'](arg1);
}

export function RotateAutomationToken() {
  return window['go']['main']['App']['RotateAutomationToken']();
}

export function SaveUserScript(arg1, arg2) {
  return window['go']['main']['App']['SaveUserScript'](arg1, arg2);
}

export function SetAutomationEnabled(arg1) {
  return window['go']['main']['App']['SetAutomationEnabled'](arg1);
}

export function SetExtensionEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetExtensionEnabled'](arg1, arg2);
}

export function SetProfileExtensions(arg1, arg2) {
  return window['go']['main']['App']['SetProfileExtensions'](arg1, arg2);
}

export function SetProfileScripts(arg1, arg2) {
  return window['go']['main']['App']['SetProfileScripts'](arg1, arg2);
}

export function SetUserScriptEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetUserScriptEnabled'](arg1, arg2);
}

export function SetUserScriptWorld(arg1, arg2) {
  return window['go']['main']['App']['SetUserScriptWorld'](arg1, arg2);
}

export function StartAutomationSession(arg1, arg2) {
  return window['go']['main']['App']['StartAutomationSession'](arg1, arg2);
}

export function StopAutomationSession(arg1) {
  return window['go']['main']['App']['StopAutomationSession'](arg1);
}

export function SyncCookies(arg1) {
  return window['go']['main']['App']['SyncCookies'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function TestProxyEntry(arg1) {
  return window['go']['main']['App']['TestProxyEntry'](arg1);
}

export function UnregisterAsDefaultBrowser() {
  return window['go']['main']['App']['UnregisterAsDefaultBrowser']();
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateProxy(arg1) {
  return window['go']['main']['App']['UpdateProxy'](arg1);
}

export function InstallFromDroppedPaths(arg1) {
  return window['go']['main']['App']['InstallFromDroppedPaths'](arg1);
}
