// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProxy(arg1:string,arg2:string):Promise<main.ProxyEntry>;

export function CreateDesktopShortcut():Promise<void>;

export function CreateProfile(arg1:string,arg2:string,arg3:string):Promise<main.BrowserProfile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteProxy(arg1:string):Promise<void>;

export function ExportCookies(arg1:string):Promise<void>;

export function ExportProfile(arg1:string):Promise<void>;

export function GetProfiles():Promise<Array<main.BrowserProfile>>;

export function GetProxies():Promise<Array<main.ProxyEntry>>;

export function GetStorageDirectory():Promise<string>;

export function GetStorageMode():Promise<string>;

export function GetStartupURL():Promise<string>;

export function ImportCookiesFromFile():Promise<string>;

export function ImportProfile():Promise<void>;

export function LaunchBrowser(arg1:string,arg2:string):Promise<void>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function OpenDefaultAppsSettings():Promise<void>;

export function OpenDataDirectory():Promise<void>;

export function RegisterAsDefaultBrowser():Promise<string>;

export function ResetCookies(arg1:string):Promise<void>;

export function SyncCookies(arg1:string):Promise<void>;

export function TestProxy(arg1:string):Promise<string>;

export function TestProxyEntry(arg1:string):Promise<string>;

export function UnregisterAsDefaultBrowser():Promise<string>;

export function UpdateProfile(arg1:main.BrowserProfile):Promise<void>;

export function UpdateProxy(arg1:main.ProxyEntry):Promise<void>;
